<?php

namespace Jankx\Extensions\NotesForPostType\Admin;

use Jankx\Extensions\NotesForPostType\Services\NotesService;

/**
 * Notes MetaBoxes
 *
 * Adds a "Ghi chú" (Notes) metabox with a WordPress classic editor (TinyMCE)
 * to every post type configured to support notes in the Theme Options panel.
 *
 * @package Jankx\Extensions\NotesForPostType\Admin
 */
class NotesMetaBoxes
{
    const NONCE_NAME = 'jankx_notes_meta_nonce';
    const NONCE_ACTION = 'jankx_notes_meta_action';

    const FIELD_NAME = 'jankx_notes';

    /**
     * Editor ID for wp_editor() — must NOT contain underscores or hyphens.
     * The textarea_name (form field) remains FIELD_NAME ('jankx_notes').
     */
    const EDITOR_ID = 'jankxnotes';

    /**
     * @var NotesService
     */
    protected $service;

    public function __construct(NotesService $service)
    {
        $this->service = $service;
    }

    public function register(): void
    {
        add_action('add_meta_boxes', [$this, 'addMetaBoxes']);
        add_action('save_post', [$this, 'saveMetaBoxes']);
        // Enqueue TinyMCE scripts before the page renders so the inline init
        // script generated by wp_editor() finds them already loaded.
        add_action('admin_enqueue_scripts', [$this, 'enqueueEditorScripts']);
    }

    /**
     * Load the WP classic editor scripts on post edit screens.
     *
     * @param string $hookSuffix Current admin page hook suffix.
     */
    public function enqueueEditorScripts(string $hookSuffix): void
    {
        if (!in_array($hookSuffix, ['post.php', 'post-new.php'], true)) {
            return;
        }
        if (!$this->service->isEnabled()) {
            return;
        }
        wp_enqueue_editor();
    }

    /**
     * Register the notes metabox for every post type selected in theme options.
     */
    public function addMetaBoxes(): void
    {
        if (!$this->service->isEnabled()) {
            return;
        }

        foreach ($this->service->getAllowedPostTypes() as $postType) {
            add_meta_box(
                'jankx_notes',
                __('Ghi chú', 'jankx'),
                [$this, 'renderMetaBox'],
                $postType,
                'normal',
                'high'
            );
        }
    }

    /**
     * Render the notes metabox with a WordPress classic editor (TinyMCE).
     *
     * @param \WP_Post $post Current post object.
     */
    public function renderMetaBox(\WP_Post $post): void
    {
        wp_nonce_field(self::NONCE_ACTION, self::NONCE_NAME);

        $note = $this->service->getNote($post->ID);

        // NOTE: wp_editor() editor ID must NOT contain underscores — use
        // EDITOR_ID ('jankxnotes') for the element ID while keeping the form
        // field name (textarea_name) as FIELD_NAME ('jankx_notes').
        wp_editor($note, self::EDITOR_ID, [
            'textarea_name' => self::FIELD_NAME,
            'textarea_rows' => 10,
            'media_buttons' => false,
            'teeny'         => false,
            'quicktags'     => true,
            'tinymce'       => [
                'toolbar1' => 'bold,italic,underline,strikethrough,bullist,numlist,blockquote,hr,link,unlink,undo,redo',
                'toolbar2' => '',
            ],
        ]);
    }

    /**
     * Save the note when the post is saved.
     *
     * @param int $postId Post ID.
     */
    public function saveMetaBoxes(int $postId): void
    {
        if (!isset($_POST[self::NONCE_NAME]) || !wp_verify_nonce($_POST[self::NONCE_NAME], self::NONCE_ACTION)) {
            return;
        }
        if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) {
            return;
        }
        if (!current_user_can('edit_post', $postId)) {
            return;
        }

        $note = isset($_POST[self::FIELD_NAME])
            ? wp_kses_post(wp_unslash($_POST[self::FIELD_NAME]))
            : '';

        $this->service->saveNote($postId, $note);
    }
}